// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package todoPb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ToDoContent struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Datetime             int64    `protobuf:"varint,3,opt,name=datetime,proto3" json:"datetime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToDoContent) Reset()         { *m = ToDoContent{} }
func (m *ToDoContent) String() string { return proto.CompactTextString(m) }
func (*ToDoContent) ProtoMessage()    {}
func (*ToDoContent) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *ToDoContent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToDoContent.Unmarshal(m, b)
}
func (m *ToDoContent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToDoContent.Marshal(b, m, deterministic)
}
func (m *ToDoContent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToDoContent.Merge(m, src)
}
func (m *ToDoContent) XXX_Size() int {
	return xxx_messageInfo_ToDoContent.Size(m)
}
func (m *ToDoContent) XXX_DiscardUnknown() {
	xxx_messageInfo_ToDoContent.DiscardUnknown(m)
}

var xxx_messageInfo_ToDoContent proto.InternalMessageInfo

func (m *ToDoContent) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ToDoContent) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ToDoContent) GetDatetime() int64 {
	if m != nil {
		return m.Datetime
	}
	return 0
}

type ToDoDetail struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Datetime             int64    `protobuf:"varint,3,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Created              int64    `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              int64    `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ToDoDetail) Reset()         { *m = ToDoDetail{} }
func (m *ToDoDetail) String() string { return proto.CompactTextString(m) }
func (*ToDoDetail) ProtoMessage()    {}
func (*ToDoDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{1}
}

func (m *ToDoDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ToDoDetail.Unmarshal(m, b)
}
func (m *ToDoDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ToDoDetail.Marshal(b, m, deterministic)
}
func (m *ToDoDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ToDoDetail.Merge(m, src)
}
func (m *ToDoDetail) XXX_Size() int {
	return xxx_messageInfo_ToDoDetail.Size(m)
}
func (m *ToDoDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_ToDoDetail.DiscardUnknown(m)
}

var xxx_messageInfo_ToDoDetail proto.InternalMessageInfo

func (m *ToDoDetail) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ToDoDetail) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ToDoDetail) GetDatetime() int64 {
	if m != nil {
		return m.Datetime
	}
	return 0
}

func (m *ToDoDetail) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ToDoDetail) GetUpdated() int64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func init() {
	proto.RegisterType((*ToDoContent)(nil), "ToDoContent")
	proto.RegisterType((*ToDoDetail)(nil), "ToDoDetail")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 182 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xc9, 0x4f, 0xc9,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x0a, 0xe6, 0xe2, 0x0e, 0xc9, 0x77, 0xc9, 0x77, 0xce,
	0xcf, 0x2b, 0x49, 0xcd, 0x2b, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0x60, 0x0e, 0x62, 0xca, 0x4c, 0x11, 0x92, 0xe0, 0x62, 0x4f, 0x86, 0x48, 0x49, 0x30, 0x29, 0x30,
	0x6a, 0x70, 0x06, 0xc1, 0xb8, 0x42, 0x52, 0x5c, 0x1c, 0x29, 0x89, 0x25, 0xa9, 0x25, 0x99, 0xb9,
	0xa9, 0x12, 0xcc, 0x60, 0xf5, 0x70, 0xbe, 0x52, 0x1b, 0x23, 0x17, 0x17, 0xc8, 0x54, 0x97, 0xd4,
	0x92, 0xc4, 0xcc, 0x1c, 0xea, 0x18, 0x0a, 0xd6, 0x55, 0x94, 0x9a, 0x58, 0x92, 0x9a, 0x22, 0xc1,
	0x02, 0x96, 0x82, 0x71, 0x41, 0x32, 0xa5, 0x05, 0x29, 0x60, 0x19, 0x56, 0x88, 0x0c, 0x94, 0x6b,
	0x64, 0xc8, 0xc5, 0x02, 0x72, 0x87, 0x90, 0x26, 0x17, 0x97, 0x33, 0x58, 0x31, 0x98, 0xc7, 0xa3,
	0x87, 0xe4, 0x65, 0x29, 0x6e, 0x3d, 0x84, 0x53, 0x95, 0x18, 0x9c, 0x38, 0xa2, 0xd8, 0x40, 0xc1,
	0x13, 0x90, 0x94, 0xc4, 0x06, 0x0e, 0x21, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2c, 0xc0,
	0x15, 0x93, 0x2f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ToDoClient is the client API for ToDo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ToDoClient interface {
	CreateToDo(ctx context.Context, in *ToDoContent, opts ...grpc.CallOption) (*ToDoDetail, error)
}

type toDoClient struct {
	cc *grpc.ClientConn
}

func NewToDoClient(cc *grpc.ClientConn) ToDoClient {
	return &toDoClient{cc}
}

func (c *toDoClient) CreateToDo(ctx context.Context, in *ToDoContent, opts ...grpc.CallOption) (*ToDoDetail, error) {
	out := new(ToDoDetail)
	err := c.cc.Invoke(ctx, "/ToDo/CreateToDo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ToDoServer is the server API for ToDo service.
type ToDoServer interface {
	CreateToDo(context.Context, *ToDoContent) (*ToDoDetail, error)
}

// UnimplementedToDoServer can be embedded to have forward compatible implementations.
type UnimplementedToDoServer struct {
}

func (*UnimplementedToDoServer) CreateToDo(ctx context.Context, req *ToDoContent) (*ToDoDetail, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateToDo not implemented")
}

func RegisterToDoServer(s *grpc.Server, srv ToDoServer) {
	s.RegisterService(&_ToDo_serviceDesc, srv)
}

func _ToDo_CreateToDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToDoContent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ToDoServer).CreateToDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ToDo/CreateToDo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ToDoServer).CreateToDo(ctx, req.(*ToDoContent))
	}
	return interceptor(ctx, in, info, handler)
}

var _ToDo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ToDo",
	HandlerType: (*ToDoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateToDo",
			Handler:    _ToDo_CreateToDo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todo.proto",
}
