// protoc --go_out=./pb --go-grpc_out=./pb proto/* && protoc-go-inject-tag -XXX_skip=xorm -input=./pb/todoPb/toDoList.pb.go

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/toDoList.proto

package todoPb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ToDoListPage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *ToDoListPage) Reset() {
	*x = ToDoListPage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_toDoList_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToDoListPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToDoListPage) ProtoMessage() {}

func (x *ToDoListPage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toDoList_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToDoListPage.ProtoReflect.Descriptor instead.
func (*ToDoListPage) Descriptor() ([]byte, []int) {
	return file_proto_toDoList_proto_rawDescGZIP(), []int{0}
}

func (x *ToDoListPage) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ToDoListResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Record int64 `protobuf:"varint,1,opt,name=record,proto3" json:"record,omitempty"`
}

func (x *ToDoListResult) Reset() {
	*x = ToDoListResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_toDoList_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToDoListResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToDoListResult) ProtoMessage() {}

func (x *ToDoListResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toDoList_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToDoListResult.ProtoReflect.Descriptor instead.
func (*ToDoListResult) Descriptor() ([]byte, []int) {
	return file_proto_toDoList_proto_rawDescGZIP(), []int{1}
}

func (x *ToDoListResult) GetRecord() int64 {
	if x != nil {
		return x.Record
	}
	return 0
}

type ToDoListContent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: form:"id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" form:"id"`
	// @inject_tag: form:"content"
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty" form:"content"`
	// @inject_tag: form:"datetime"
	Datetime int64 `protobuf:"varint,3,opt,name=datetime,proto3" json:"datetime,omitempty" form:"datetime"`
}

func (x *ToDoListContent) Reset() {
	*x = ToDoListContent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_toDoList_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToDoListContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToDoListContent) ProtoMessage() {}

func (x *ToDoListContent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toDoList_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToDoListContent.ProtoReflect.Descriptor instead.
func (*ToDoListContent) Descriptor() ([]byte, []int) {
	return file_proto_toDoList_proto_rawDescGZIP(), []int{2}
}

func (x *ToDoListContent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ToDoListContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ToDoListContent) GetDatetime() int64 {
	if x != nil {
		return x.Datetime
	}
	return 0
}

type ToDoListByPage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Todolist []*ToDoListContent `protobuf:"bytes,1,rep,name=todolist,proto3" json:"todolist,omitempty"`
}

func (x *ToDoListByPage) Reset() {
	*x = ToDoListByPage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_toDoList_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToDoListByPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToDoListByPage) ProtoMessage() {}

func (x *ToDoListByPage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toDoList_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToDoListByPage.ProtoReflect.Descriptor instead.
func (*ToDoListByPage) Descriptor() ([]byte, []int) {
	return file_proto_toDoList_proto_rawDescGZIP(), []int{3}
}

func (x *ToDoListByPage) GetTodolist() []*ToDoListContent {
	if x != nil {
		return x.Todolist
	}
	return nil
}

type ToDoListDetail struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: form:"id" xorm:"'id' not null pk autoincr"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" form:"id" xorm:"'id' not null pk autoincr"`
	// @inject_tag: form:"content" xorm:"'content' varchar(300) not null default ''"
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty" form:"content" xorm:"'content' varchar(300) not null default ''"`
	// @inject_tag: form:"datetime" xorm:"'datetime' int(10) not null default 0"
	Datetime int64 `protobuf:"varint,3,opt,name=datetime,proto3" json:"datetime,omitempty" form:"datetime" xorm:"'datetime' int(10) not null default 0"`
	// @inject_tag: xorm:"'created_at' created"
	Created int64 `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty" xorm:"'created_at' created"`
	// @inject_tag: xorm:"'updated_at' updated"
	Updated int64 `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty" xorm:"'updated_at' updated"`
	// @inject_tag: xorm:"'deleted_at' deleted"
	Deleted int64 `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty" xorm:"'deleted_at' deleted"`
}

func (x *ToDoListDetail) Reset() {
	*x = ToDoListDetail{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_toDoList_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToDoListDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToDoListDetail) ProtoMessage() {}

func (x *ToDoListDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_toDoList_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToDoListDetail.ProtoReflect.Descriptor instead.
func (*ToDoListDetail) Descriptor() ([]byte, []int) {
	return file_proto_toDoList_proto_rawDescGZIP(), []int{4}
}

func (x *ToDoListDetail) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ToDoListDetail) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ToDoListDetail) GetDatetime() int64 {
	if x != nil {
		return x.Datetime
	}
	return 0
}

func (x *ToDoListDetail) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ToDoListDetail) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *ToDoListDetail) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

var File_proto_toDoList_proto protoreflect.FileDescriptor

var file_proto_toDoList_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x6f, 0x44, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x22, 0x0a, 0x0c, 0x54, 0x6f, 0x44, 0x6f, 0x4c, 0x69,
	0x73, 0x74, 0x50, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x28, 0x0a, 0x0e, 0x54, 0x6f,
	0x44, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x22, 0x57, 0x0a, 0x0f, 0x54, 0x6f, 0x44, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x61, 0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x22, 0x3e, 0x0a,
	0x0e, 0x54, 0x6f, 0x44, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x79, 0x50, 0x61, 0x67, 0x65, 0x12,
	0x2c, 0x0a, 0x08, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x54, 0x6f, 0x44, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x52, 0x08, 0x74, 0x6f, 0x64, 0x6f, 0x6c, 0x69, 0x73, 0x74, 0x22, 0xa4, 0x01,
	0x0a, 0x0e, 0x54, 0x6f, 0x44, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61,
	0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x61,
	0x74, 0x65, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x64, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x64, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x64, 0x32, 0x72, 0x0a, 0x08, 0x54, 0x6f, 0x44, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x34, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x6f, 0x44, 0x6f, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x0f, 0x2e, 0x54, 0x6f, 0x44, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x1a, 0x0f, 0x2e, 0x54, 0x6f, 0x44, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0c, 0x52, 0x65, 0x61, 0x64, 0x54, 0x6f,
	0x44, 0x6f, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x0d, 0x2e, 0x54, 0x6f, 0x44, 0x6f, 0x4c, 0x69, 0x73,
	0x74, 0x50, 0x61, 0x67, 0x65, 0x1a, 0x0f, 0x2e, 0x54, 0x6f, 0x44, 0x6f, 0x4c, 0x69, 0x73, 0x74,
	0x42, 0x79, 0x50, 0x61, 0x67, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x74, 0x6f,
	0x64, 0x6f, 0x50, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_toDoList_proto_rawDescOnce sync.Once
	file_proto_toDoList_proto_rawDescData = file_proto_toDoList_proto_rawDesc
)

func file_proto_toDoList_proto_rawDescGZIP() []byte {
	file_proto_toDoList_proto_rawDescOnce.Do(func() {
		file_proto_toDoList_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_toDoList_proto_rawDescData)
	})
	return file_proto_toDoList_proto_rawDescData
}

var file_proto_toDoList_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_toDoList_proto_goTypes = []interface{}{
	(*ToDoListPage)(nil),    // 0: ToDoListPage
	(*ToDoListResult)(nil),  // 1: ToDoListResult
	(*ToDoListContent)(nil), // 2: ToDoListContent
	(*ToDoListByPage)(nil),  // 3: ToDoListByPage
	(*ToDoListDetail)(nil),  // 4: ToDoListDetail
}
var file_proto_toDoList_proto_depIdxs = []int32{
	2, // 0: ToDoListByPage.todolist:type_name -> ToDoListContent
	4, // 1: ToDoList.CreateToDoList:input_type -> ToDoListDetail
	0, // 2: ToDoList.ReadToDoList:input_type -> ToDoListPage
	1, // 3: ToDoList.CreateToDoList:output_type -> ToDoListResult
	3, // 4: ToDoList.ReadToDoList:output_type -> ToDoListByPage
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_toDoList_proto_init() }
func file_proto_toDoList_proto_init() {
	if File_proto_toDoList_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_toDoList_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToDoListPage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_toDoList_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToDoListResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_toDoList_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToDoListContent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_toDoList_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToDoListByPage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_toDoList_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToDoListDetail); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_toDoList_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_toDoList_proto_goTypes,
		DependencyIndexes: file_proto_toDoList_proto_depIdxs,
		MessageInfos:      file_proto_toDoList_proto_msgTypes,
	}.Build()
	File_proto_toDoList_proto = out.File
	file_proto_toDoList_proto_rawDesc = nil
	file_proto_toDoList_proto_goTypes = nil
	file_proto_toDoList_proto_depIdxs = nil
}
